name: Build
on: [ push, pull_request ]
jobs:

  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      
      - name: Build and deploy with Gradle
        if: github.ref == 'refs/heads/main'
        run: ./gradlew build publishAll --no-daemon --info --stacktrace
        env:
          # Sign artifacts
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
          # Authenticate to OSSRH
          ORG_GRADLE_PROJECT_ossrhUser: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
          # Authenticate to GPP
          ORG_GRADLE_PROJECT_gradle.publish.key: ${{ secrets.GPP_KEY }}
          ORG_GRADLE_PROJECT_gradle.publish.secret: ${{ secrets.GPP_SECRET }}
      
      - name: Build with Gradle
        if: github.ref != 'refs/heads/main'
        run: ./gradlew build --no-daemon --info --stacktrace

      - name: Build Gradle War Sample
        working-directory: ./samples/gradle-war-sample
        run: ./gradlew build -PcicsUser=user -PcicsPass=pass --no-daemon --info --stacktrace

      - name: Build Gradle Multipart Sample
        working-directory: ./samples/gradle-multipart-sample
        run: ./gradlew build -PcicsUser=user -PcicsPass=pass --no-daemon --info --stacktrace